spring:
  datasource:
    name: wrmidb
    url: jdbc:mysql://47.99.122.131:3306/sjzl?useUnicode=true&characterEncoding=UTF-8&connectTimeout=1000&autoReconnect=true&useTimezone=true&serverTimezone=GMT%2B8&useSSL=false
    username: sjzl
    password: sjzl123!@# #公网
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: 47.99.123.144
    port: 6579
    database: 0
    password: sjzl123!@#
  devtools:
    restart:
      trigger-file: trigger.txt


#是否请求加密
encryptionData: true